# Add your additional Hyprland configurations here

# ==============================
# GPU Assignments
# ==============================
# Notes:
# - Use `lspci -d ::03xx` to list all GPU devices
# - See udev rules located at `/etc/udev/rules.d/99-dri-gpu-symlinks.rules` for AMD RX 7700S/iGPU udev assignments
# - See doc page: https://wiki.hypr.land/Configuring/Multi-GPU/#creating-consistent-device-paths-for-specific-cards
env = AQ_DRM_DEVICES,/dev/dri/card-amd-rx7700s:/dev/dri/card-amd-igpu
# old mehod: env = AQ_DRM_DEVICES,/dev/dri/card1:/dev/dri/card2

# SDL version
env = SDL_VIDEODRIVER,wayland

# No Hardware Cursor
cursor {
    no_hardware_cursors = false
}

# Start on workspace 
exec-once = hyprctl dispatch workspace 1

# Blur for waybar
#layerrule = blur, waybar

# Uncomment in case you have issues with screensharing
# exec-once = ~/.config/hypr/scripts/xdg.sh

# Enable hdr1
#experimental {
#    xx_color_management_v4=true
#}

# Force Vulkan renderer
env = WLR_RENDERER,vulkan

# env = LIBVA_DRIVER_NAME,nvidia
# env = XDG_SESSION_TYPE,wayland
# env = GBM_BACKEND,nvidia-drm
# env = __GLX_VENDOR_LIBRARY_NAME,nvidia
# env = NVD_BACKEND,direct
# Screen toggle bindings (Ryan's custom)
bind = $mainMod CTRL, Z, exec, $HYPRSCRIPTS/set-screen-disabled.sh false                  # Toggle laptop screen on
